{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyOEigkDvmF9iN/iWwFWgpSw",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "ir",
      "display_name": "R"
    },
    "language_info": {
      "name": "R"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/Krishan-s8/Partitioning-Clustering-Analysis-of-White-Wine-Chemical-and-Sensory-Properties/blob/main/Partitioning_Clustering_Analysis_of_White_Wine_R.R\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "ch7c3bUOIt_U"
      },
      "outputs": [],
      "source": [
        "library(dplyr)\n",
        "library(readxl)\n",
        "library(factoextra)\n",
        "library(NbClust)\n",
        "library(caret)\n",
        "library(e1071)\n",
        "\n",
        "\n",
        "# Importing the Data set\n",
        "library(readxl)\n",
        "whitewine_data <- read_excel(\"C:/Users/krishan_s/Desktop/ML/Assessmet/Whitewine_v6.xlsx\")\n",
        "\n",
        "# number of data check\n",
        "dim(whitewine_data)\n",
        "\n",
        "# Checking for is there are any na values\n",
        "sum(is.na(whitewine_data))\n",
        "\n",
        "# a)\n",
        "\n",
        "# using the box plot method to check outliers\n",
        "boxplot(whitewine_data[,-12])\n",
        "\n",
        "# first column outliers removal\n",
        "IQR_FA <- IQR(whitewine_data$`fixed acidity`)\n",
        "lower_FA = quantile(whitewine_data$`fixed acidity`, .25) - 1.5*IQR_FA\n",
        "upper_FA = quantile(whitewine_data$`fixed acidity`, .75) + 1.5*IQR_FA\n",
        "\n",
        "# second column outliers removal\n",
        "IQR_VA <- IQR(whitewine_data$`volatile acidity`)\n",
        "lower_VA = quantile(whitewine_data$`volatile acidity`, .25) - 1.5*IQR_VA\n",
        "upper_VA = quantile(whitewine_data$`volatile acidity`, .75) + 1.5*IQR_VA\n",
        "\n",
        "# 3 column outliers removal\n",
        "IQR_CA <- IQR(whitewine_data$`citric acid`)\n",
        "lower_CA = quantile(whitewine_data$`citric acid`, .25) - 1.5*IQR_CA\n",
        "upper_CA = quantile(whitewine_data$`citric acid`, .75) + 1.5*IQR_CA\n",
        "\n",
        "# 4 column outliers removal\n",
        "IQR_RS <- IQR(whitewine_data$`residual sugar`)\n",
        "lower_RS = quantile(whitewine_data$`residual sugar`, .25) - 1.5*IQR_RS\n",
        "upper_RS = quantile(whitewine_data$`residual sugar`, .75) + 1.5*IQR_RS\n",
        "\n",
        "# 5 column outliers removal\n",
        "IQR_CL <- IQR(whitewine_data$chlorides)\n",
        "lower_CL = quantile(whitewine_data$chlorides, .25) - 1.5*IQR_CL\n",
        "upper_CL = quantile(whitewine_data$chlorides, .75) + 1.5*IQR_CL\n",
        "\n",
        "# 6 column outliers removal\n",
        "IQR_FSD <- IQR(whitewine_data$`free sulfur dioxide`)\n",
        "lower_FSD = quantile(whitewine_data$`free sulfur dioxide`, .25) - 1.5*IQR_FSD\n",
        "upper_FSD = quantile(whitewine_data$`free sulfur dioxide`, .75) + 1.5*IQR_FSD\n",
        "\n",
        "# 7 column outliers removal\n",
        "IQR_TSD <- IQR(whitewine_data$`total sulfur dioxide`)\n",
        "lower_TSD = quantile(whitewine_data$`total sulfur dioxide`, .25) - 1.5*IQR_TSD\n",
        "upper_TSD = quantile(whitewine_data$`total sulfur dioxide`, .75) + 1.5*IQR_TSD\n",
        "\n",
        "# 8 column outliers removal\n",
        "IQR_DE <- IQR(whitewine_data$density)\n",
        "lower_DE = quantile(whitewine_data$density, .25) - 1.5*IQR_DE\n",
        "upper_DE = quantile(whitewine_data$density, .75) + 1.5*IQR_DE\n",
        "\n",
        "# 9 column outliers removal\n",
        "IQR_PH <- IQR(whitewine_data$pH)\n",
        "lower_PH = quantile(whitewine_data$pH, .25) - 1.5*IQR_PH\n",
        "upper_PH = quantile(whitewine_data$pH, .75) + 1.5*IQR_PH\n",
        "\n",
        "# 10 column outliers removal\n",
        "IQR_SUL <- IQR(whitewine_data$sulphates)\n",
        "lower_SUL = quantile(whitewine_data$sulphates, .25) - 1.5*IQR_SUL\n",
        "upper_SUL = quantile(whitewine_data$sulphates, .75) + 1.5*IQR_SUL\n",
        "\n",
        "# 11 column outliers removal\n",
        "IQR_AL <- IQR(whitewine_data$alcohol)\n",
        "lower_AL = quantile(whitewine_data$alcohol, .25) - 1.5*IQR_AL\n",
        "upper_AL = quantile(whitewine_data$alcohol, .75) + 1.5*IQR_AL\n",
        "\n",
        "updated_whitewine <- subset(whitewine_data, whitewine_data$`fixed acidity` >= lower_FA\n",
        "                            & whitewine_data$`fixed acidity` <= upper_FA\n",
        "                            & whitewine_data$`volatile acidity` >= lower_VA\n",
        "                            & whitewine_data$`volatile acidity` <= upper_VA\n",
        "                            & whitewine_data$`citric acid` >= lower_CA\n",
        "                            & whitewine_data$`citric acid` <= upper_CA\n",
        "                            & whitewine_data$`residual sugar` >= lower_RS\n",
        "                            & whitewine_data$`residual sugar` <= upper_RS\n",
        "                            & whitewine_data$chlorides >= lower_CL\n",
        "                            & whitewine_data$chlorides <= upper_CL\n",
        "                            & whitewine_data$`free sulfur dioxide` >= lower_FSD\n",
        "                            & whitewine_data$`free sulfur dioxide` <= upper_FSD\n",
        "                            & whitewine_data$`total sulfur dioxide` >= lower_TSD\n",
        "                            & whitewine_data$`total sulfur dioxide` <= upper_TSD\n",
        "                            & whitewine_data$density >= lower_DE\n",
        "                            & whitewine_data$density <= upper_DE\n",
        "                            & whitewine_data$pH >= lower_PH\n",
        "                            & whitewine_data$pH <= upper_PH\n",
        "                            & whitewine_data$sulphates >= lower_SUL\n",
        "                            & whitewine_data$sulphates <= upper_SUL\n",
        "                            & whitewine_data$alcohol >= lower_AL\n",
        "                            & whitewine_data$alcohol <= upper_AL)\n",
        "\n",
        "# Boxplot\n",
        "boxplot(updated_whitewine)\n",
        "\n",
        "# Plotting the box plot for before and after removing outliers\n",
        "boxplot(whitewine_data[,1])\n",
        "boxplot(updated_whitewine[,1])\n",
        "\n",
        "boxplot(whitewine_data[,2])\n",
        "boxplot(updated_whitewine[,2])\n",
        "\n",
        "boxplot(whitewine_data[,3])\n",
        "boxplot(updated_whitewine[,3])\n",
        "\n",
        "boxplot(whitewine_data[,4])\n",
        "boxplot(updated_whitewine[,4])\n",
        "\n",
        "boxplot(whitewine_data[,5])\n",
        "boxplot(updated_whitewine[,5])\n",
        "\n",
        "boxplot(whitewine_data[,6])\n",
        "boxplot(updated_whitewine[,6])\n",
        "\n",
        "boxplot(whitewine_data[,7])\n",
        "boxplot(updated_whitewine[,7])\n",
        "\n",
        "boxplot(whitewine_data[,8])\n",
        "boxplot(updated_whitewine[,8])\n",
        "\n",
        "boxplot(whitewine_data[,9])\n",
        "boxplot(updated_whitewine[,9])\n",
        "\n",
        "boxplot(whitewine_data[,10])\n",
        "boxplot(updated_whitewine[,10])\n",
        "\n",
        "boxplot(whitewine_data[,11])\n",
        "boxplot(updated_whitewine[,11])\n",
        "\n",
        "\n",
        "# Normalizing the data ( Scaling )\n",
        "# Creating a new function called normalize\n",
        "normalize <- function(x){\n",
        "  return ((x - min(x))/(max(x) - min(x)))\n",
        "}\n",
        "\n",
        "WhitewineNormalize <- as.data.frame(lapply(updated_whitewine, normalize))\n",
        "whiteNormUpdated <- WhitewineNormalize[,-12]\n",
        "boxplot(whiteNormUpdated)\n",
        "\n",
        "# b)\n",
        "\n",
        "# Determine the optimal number of clusters using automated methods\n",
        "# NBclust\n",
        "library(NbClust)\n",
        "nb_clusters <- NbClust(data = whiteNormUpdated, distance = \"euclidean\", min.nc = 2, max.nc = 10, method = \"kmeans\")\n",
        "\n",
        "library(factoextra)\n",
        "\n",
        "# Elbow method to determine the number of clusters\n",
        "elbow_plot <- fviz_nbclust(whiteNormUpdated, kmeans, method = \"wss\") +\n",
        "  geom_vline(xintercept = 4, linetype = 2) +  # Add a vertical line at k = 4\n",
        "  labs(subtitle = \"Elbow method\")\n",
        "\n",
        "print(elbow_plot)\n",
        "\n",
        "# Gap Statistics\n",
        "library(cluster)\n",
        "gap_stat <- clusGap(whiteNormUpdated, FUN = kmeans, nstart = 25, K.max = 10, B = 50)\n",
        "\n",
        "fviz_gap_stat(gap_stat)\n",
        "\n",
        "# Silhouette Method\n",
        "fviz_nbclust(whiteNormUpdated, kmeans,method = \"silhouette\") + labs(subtitle = \"Silhouette method\")\n",
        "\n",
        "# c)\n",
        "\n",
        "# Find the most favored k from the automated methods\n",
        "fav_k <- list(NBclust = nb_clusters$Best.nc[1],\n",
        "              Elbow = which.min(wcss),\n",
        "              Gap_Statistics = which.max(gap_stat$Tab[, \"gap\"]),\n",
        "              Silhouette = which.max(silhouette[2:10]))\n",
        "\n",
        "print(fav_k)\n",
        "\n",
        "# Select the most common k among the favored k values\n",
        "most_common_k <- names(sort(table(unlist(fav_k)), decreasing = TRUE))[1]\n",
        "\n",
        "print(most_common_k)\n",
        "\n",
        "# Perform K-means clustering with the most favored k\n",
        "kmeans_model <- kmeans(whiteNormUpdated, centers = as.numeric(most_common_k))\n",
        "\n",
        "# Print K-means model summary\n",
        "print(kmeans_model)\n",
        "\n",
        "# Extract cluster centers\n",
        "cluster_centers <- kmeans_model$centers\n",
        "print(cluster_centers)\n",
        "\n",
        "# Assign clusters to each data point\n",
        "cluster_assignments <- kmeans_model$cluster\n",
        "print(cluster_assignments)\n",
        "\n",
        "# Compute Within-Cluster Sum of Squares (WSS)\n",
        "wss <- kmeans_model$tot.withinss\n",
        "print(paste(\"Within-Cluster Sum of Squares (WSS):\", wss))\n",
        "\n",
        "# Compute Between-Cluster Sum of Squares (BSS)\n",
        "tss <- sum(kmeans_model$tot.withinss) +\n",
        "  sum((apply(whiteNormUpdated, 2, mean) - cluster_centers)^2) * nrow(whiteNormUpdated)\n",
        "\n",
        "bss <- tss - wss\n",
        "print(paste(\"Between-Cluster Sum of Squares (BSS):\", bss))\n",
        "\n",
        "# Compute Ratio of BSS over TSS\n",
        "bss_tss_ratio <- bss / tss\n",
        "print(paste(\"Ratio of BSS over TSS:\", bss_tss_ratio))\n",
        "\n",
        "########################################################################################################\n",
        "\n",
        "# e)\n",
        "\n",
        "# Perform PCA\n",
        "pca_result <- prcomp(whiteNormUpdated, scale = TRUE)\n",
        "\n",
        "# Extract eigenvalues and eigenvectors\n",
        "eigenvalues <- pca_result$sdev^2\n",
        "eigenvectors <- pca_result$rotation\n",
        "\n",
        "# Print eigenvalues and eigenvectors\n",
        "print(\"Eigenvalues:\")\n",
        "print(eigenvalues)\n",
        "print(\"Eigenvectors:\")\n",
        "print(eigenvectors)\n",
        "\n",
        "# Compute cumulative score per principal component\n",
        "cumulative_score <- cumsum(pca_result$sdev^2 / sum(pca_result$sdev^2) * 100)\n",
        "\n",
        "# Print cumulative score\n",
        "print(\"Cumulative Score per Principal Component:\")\n",
        "print(cumulative_score)\n",
        "\n",
        "# Find the number of principal components with cumulative score > 85%\n",
        "num_components <- which(cumulative_score > 85)[1]\n",
        "\n",
        "# Extract the required principal components\n",
        "transformed_data <- as.data.frame(pca_result$x[, 1:num_components])\n",
        "\n",
        "# Print the transformed dataset\n",
        "print(\"Transformed Dataset with Principal Components:\")\n",
        "print(transformed_data)\n",
        "\n",
        "# f)\n",
        "\n",
        "# Perform k-means clustering on PCA-transformed dataset\n",
        "kmeans_model <- kmeans(transformed_data, centers = 2, nstart = 25)\n",
        "\n",
        "# Apply NBclust method\n",
        "nbclust_out <- NbClust(transformed_data, distance = \"euclidean\", min.nc = 2, max.nc = 10, method = \"kmeans\")\n",
        "print(nbclust_out)\n",
        "\n",
        "# Visualize NBclust results\n",
        "fviz_nbclust(nbclust_out)\n",
        "\n",
        "# Elbow Method\n",
        "fviz_nbclust(transformed_data, kmeans, method = \"wss\")\n",
        "\n",
        "# Gap Statistics\n",
        "fviz_nbclust(transformed_data, kmeans, method = \"gap_stat\")\n",
        "\n",
        "# Silhouette Method\n",
        "fviz_nbclust(transformed_data, kmeans, method = \"silhouette\")\n",
        "\n",
        "# Visualize clustering results\n",
        "fviz_cluster(kmeans_model, data = transformed_data)\n",
        "\n",
        "# g)\n",
        "\n",
        "# Perform k-means clustering with the most favored k value\n",
        "kmeans_result <- kmeans(transformed_data, centers = 2)  # Assuming 2 is the most favored k value\n",
        "\n",
        "# Display k-means output\n",
        "print(\"K-Means Output:\")\n",
        "print(kmeans_result)\n",
        "\n",
        "# Display cluster centers\n",
        "print(\"Cluster Centers:\")\n",
        "print(kmeans_result$centers)\n",
        "\n",
        "# Display clustered results\n",
        "print(\"Clustered Results:\")\n",
        "print(kmeans_result$cluster)\n",
        "\n",
        "# Calculate between_cluster_sums_of_squares (BSS)\n",
        "BSS <- sum((kmeans_result$centers - colMeans(transformed_data))^2)\n",
        "\n",
        "# Calculate within_cluster_sums_of_squares (WSS)\n",
        "WSS <- sum(kmeans_result$withinss)\n",
        "\n",
        "# Calculate total_sum_of_Squares (TSS)\n",
        "TSS <- BSS + WSS\n",
        "\n",
        "# Calculate BSS/TSS ratio\n",
        "BSS_TSS_ratio <- BSS / TSS\n",
        "\n",
        "# Display BSS, WSS, and BSS/TSS ratio\n",
        "print(\"Between Cluster Sum of Squares (BSS):\")\n",
        "print(BSS)\n",
        "print(\"Within Cluster Sum of Squares (WSS):\")\n",
        "print(WSS)\n",
        "print(\"Ratio of BSS over TSS:\")\n",
        "print(BSS_TSS_ratio)\n",
        "\n",
        "# h)\n",
        "\n",
        "# Generate silhouette plot\n",
        "library(cluster)\n",
        "silhouette_plot <- silhouette(kmeans_result$cluster, dist(transformed_data))\n",
        "\n",
        "# Plot silhouette plot\n",
        "plot(silhouette_plot, main = \"Silhouette Plot for K-Means Clustering\")\n",
        "\n",
        "# Calculate silhouette scores\n",
        "sil <- silhouette(kmeans_result$cluster, silhouette_plot)\n",
        "\n",
        "# Average silhouette width score\n",
        "avg_silhouette_width <- mean(sil$width)\n",
        "\n",
        "# Print average silhouette width score\n",
        "cat(\"Average Silhouette Width Score:\", avg_silhouette_width, \"\\n\")"
      ]
    }
  ]
}